name: my_cst2335_flutterlabs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  encrypted_shared_preferences: ^3.0.1
  url_launcher: ^6.2.4

  # Floor database packages
  floor: ^1.5.0
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Generates app_database.g.dart
  floor_generator: ^1.5.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - images/lightbulb.jpg
    - images/question-mark.jpg
    - images/stop.jpg